name: Build and Deploy

on:
  # ceci est un test
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ closed ] 

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    name: Build and deploy
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Test
      run: npm test
      env:
         CI: ""
    - name: Build
      run: npm run build
      env:
         CI: ""
    - name: Deploy to firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
