name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Deploy to firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
